### ISSUE TITLE
`MeshStandardMaterialParameters` missing `hexTiling` in d.ts

### ISSUE THREAD

**Issue by agargaro** [Ameobea/three-hex-tilebreaking#1]
Hi, thanks for sharing this library 😄 

Bug reproduction: https://stackblitz.com/edit/three-hex-tiling-d-ts-problem?file=src%2Fmain.ts

The bug is here: https://github.com/Ameobea/three-hex-tiling/blob/main/src/index.ts#L85

I think we can easily fix this writing `MeshStandardMaterialParameters` instead of `MeshPhysicalMaterialParameters`, because `MeshPhysicalMaterialParameters` extends `MeshStandardMaterialParameters` definitions.

If you wan I can make a PR

**Comment by Ameobea** [comment]
Ah, very good catch.  I have fixed the types and it should now work correctly for both standard + physical materials.

I messed up publishing and didn't include all of these changes in 0.1.3, so you'll need to use `three-hex-tiling` 0.1.4 which includes this fix.

Thanks again for reporting this!

**Comment by Ameobea** [comment]
I've forked your stackblitz and verified that the type error is no longer present: https://stackblitz.com/edit/three-hex-tiling-d-ts-problem-kzhuvf23?file=src%2Fmain.ts

I also updated to three.js 171 and it worked without issue

**Comment by agargaro** [comment]
Thank you very much! 😄
