### ISSUE TITLE
Compatibility with latest `three` version

### ISSUE THREAD

**Issue by agargaro** [Ameobea/three-hex-tilebreaking#2]
Hello again!

I tried the library locally with the latest version of three (0.171.0) and it works, so what about removing the maximum version check of `three`  to ensure compatibility with later versions?

```js
"peerDependencies": {
  "three": ">=0.151"
}
```

PS. I noticed that the package.json is not aligned to the latest version on npm.

**Comment by Ameobea** [comment]
Hi,

Thanks for pointing this out.  I've taken your suggestion and removed the max constraint on the `three` peer dependency.  I've also bumped the version used in the demo to latest and verified that it works as expected.

I've published `three-hex-tiling` version 0.1.3 which contains this change as well as the fix from your other issue

Thanks for opening these and providing such easy to act on and detailed descriptions - I really appreciate it

**Comment by agargaro** [comment]
Thanks to you! 😄
